'use strict';

// Reads app/.env (gitignored, local only) and writes
// src/environments/environment.local.ts (also gitignored) so the Angular
// app can import the value without ever committing a secret to git.
// Runs automatically before `npm start` / `npm run build` / `npm run watch`.

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');

if (fs.existsSync(envPath)) {
  require('dotenv').config({ path: envPath });
}

const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY ?? '';

if (!googleMapsApiKey) {
  console.warn(
    '[generate-env] GOOGLE_MAPS_API_KEY is not set in app/.env — address autocomplete will be disabled. ' +
    'Copy app/.env.example to app/.env and add your key.'
  );
}

const outputPath = path.join(rootDir, 'src/environments/environment.local.ts');

const contents = `// AUTO-GENERATED by scripts/generate-env.js from your local .env file.
// Do not edit by hand, and do not commit this file (see .gitignore).
export const environmentLocal = {
  googleMapsApiKey: ${JSON.stringify(googleMapsApiKey)}
};
`;

fs.writeFileSync(outputPath, contents);
